apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-ha-secure-webapp-sync
  namespace: default  # Or whichever namespace your app pods run in
spec:
  refreshInterval: 1h # How often to check AWS for updates
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: aws-ha-secure-webapp # This is the name of the K8s secret it will CREATE
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: eks/aws-ha-secure-webapp/db-credentials # The name you gave the secret in AWS
