apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      serviceAccountName: {{ include "serviceAccountName" . }}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          ports:
            - containerPort: {{ .Values.app.port }}
            
          readinessProbe:
            httpGet:
              path: {{ .Values.health.path }}
              port: {{ .Values.app.port }}
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: {{ .Values.health.path }}
              port: {{ .Values.app.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
            

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
