{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceAccountName" . }}
  annotations:
{{- range ,  := .Values.serviceAccount.annotations }}
    {{  }}: {{  | quote }}
{{- end }}
{{- end }}
